
services:
  text-mining-ui:
    build: .
    container_name: text-mining-ui
    environment:
      GRADIO_SERVER_NAME: 0.0.0.0
      GRADIO_SERVER_PORT: 7860
    ports:
      - "7860:7860"
    volumes:
      - ./src:/ui-app/src
      - ./models:/ui-app/models
      - ./config.py:/ui-app/config.py 
      - ./kafkaConnection:/ui-app/kafkaConnection
    command: ["python3", "/ui-app/src/app_main.py"]
    restart: unless-stopped
